import "./globals.css";
import { Inter } from "next/font/google";
import VC from "@/components/VC";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <button onClick={vc}>vConsole</button> */}
      <body className={inter.className}>{children}</body>
      <VC />
    </html>
  );
}
